#! /usr/bin/env python3
#
# Copyright © 2023 Tian Haoyu <tienhoayu@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

## grep

* --color:                               General Output Control.
                                                              (line  14)
* --colour:                              General Output Control.
                                                              (line  14)

* -v:                                    Matching Control.    (line  51)
* -w:                                    Matching Control.    (line  56)
* -x:                                    Matching Control.    (line  73)
* -y:                                    Matching Control.    (line  26)

